scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.1.109:8080']
        labels:
          application: 'My Spring Boot Application'
    basic_auth:
      username: user
      password: password
remote_write:
  - url: "http://192.168.1.109:30793/api/v1/prom/write?db=jpetstore"
    basic_auth:
      username: root
      password: root