apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-account
  name: api-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-account
  template:
    metadata:
      labels:
        app: api-account
    spec:
      containers:
      - env:
          - name: JAVA_OPTS
            value: "-Xmx150m"
        image: rawan99/api-account:latest
        name: api-account
        ports:
        - containerPort: 8080
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-account
  name: api-account
spec:
  ports:
    - name: "http"
      protocol: TCP
      nodePort: 31689
      port: 8081
      targetPort: 8080
  selector:
    app: api-account
  type: NodePort


