apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - env:
        image: rawan99/frontend:latest
        name: frontend
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
  


