apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-account
  name: mysql-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-account
  template:
    metadata:
      labels:
        app: mysql-account
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: jpetstore
            - name: MYSQL_PASSWORD
              value: test
            - name: MYSQL_ROOT_PASSWORD
              value: test
          image: mysql:8.0
          name: mysql-account
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-account-claim
      restartPolicy: Always
      volumes:
        - name: mysql-account-claim
          persistentVolumeClaim:
            claimName: mysql-account-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-account
  name: mysql-account
spec:
  ports:
    - name: "3311"
      nodePort: 30473
      port: 3311
      targetPort: 3306
  selector:
    app: mysql-account
  type: NodePort


