version: '2.1'

services:

  prometheus:
    image: prom/prometheus:v2.38.0
    network_mode: host
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"

